name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'  # Atualiza diariamente à meia-noite
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL: true
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_MASKED_TIME: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: MrJabes762/MrJabes762
          SECTION_NAME: waka
          BLOCKS: ░▒▓█
          CODE_LANG: txt
          SHOW_TIME: true
          STOP_AT_OTHER: false
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
